### PR TITLE
Damian segmentationfunction

### PR DESCRIPTION
**Pull request by DamianAtlass**
provides a default segmentation function for images using the felzenszwalb algorithm in order to create super pixels

### CODE REVIEW

**Comment by e-strauss** [comment]
thanks @DamianAtlass - is the PR still WIP or should merge it? If I should merge it, I would add one commit, which fixes the import error from the CI test

**Review by e-strauss — APPROVED** [review]
LGTM ;) - I am thinking about creating a demo folder (I got also some demo files) and move the picture to the data folder in a later PR

**Comment by DamianAtlass** [comment]
@e-strauss I thought we might fix the test issue in the future, but sure we can just throw it out

**Comment by e-strauss** [comment]
@DamianAtlass I would say just disable the test case for now, so that the pipeline doesnt crash

**Comment by e-strauss** [comment]
nicht wundern wegen dem conflict, habe in meine PR paar dependencies rausgeworfen die nicht relevant waren (die vom getting started tutorial: flux & co), um die compile time zu minimieren

**Pull request merged**
